sudo: false

language: node_js

services:
  - redis-server
  - memcached

#cache:
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - '4'
  - '5'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm run test
